### ISSUE TITLE
SNOW-587447: Wrong parameter used as sleep timer cap?

### ISSUE THREAD

**Issue by timfenten** [snowflakedb/snowflake-connector-nodejs#301]
https://github.com/snowflakedb/snowflake-connector-nodejs/blob/182b40f92af2ae6c129b1ded946aba74faa8212c/lib/services/sf.js#L1129

Hi,

its a very specific question but anyway ;-)

Why is PARAM_RETRY_SF_MAX_NUM_RETRIES used as timeout cap here?
Shouldn't it be PARAM_RETRY_SF_MAX_SLEEP_TIME?

**Comment by sfc-gh-dszmolka** [comment]
hi, reviewing the issues stumbled on this one. and to be honest, i'm not sure why :) it's a bit suspicious for sure, but i see it's the same at least for 3.5 years now since https://github.com/snowflakedb/snowflake-connector-nodejs/commit/5ddd0df706006658b548b21f64121003ecffd512

that doesn't mean it's correct, but, wasn't changed for a while now (since implementation, as i see it)
anyways we'll check it and see if a change is needed.

**Comment by sfc-gh-dszmolka** [comment]
fixed with #480 , which is already merged into main and thus will be part of the next release - expected around the second half of May

**Comment by sfc-gh-dszmolka** [comment]
fix released with version [1.6.22](https://github.com/snowflakedb/snowflake-connector-nodejs/releases/tag/v1.6.22)
