### ISSUE TITLE
Need clear example of how to cancel a query after a timeout.

### ISSUE THREAD

**Issue by ksze** [snowflakedb/snowflake-connector-nodejs#416]
Let's say I have a `SELECT` query that can be very slow. I want to be able to cancel it after a timeout in Node.js.
My preferred way to consume the result is by using this pattern:

```lang=typescript
for await (const row of statement.streamRows()) {
  /* do something */
}
```

The above is a valid pattern because `statement.streamRows()` returns a Node.js `Readable`.

I hate using the `complete`-callback style of consuming results.

The documentation says the `Statement` has a `cancel()` method, but it says nothing about the behaviour to expect.

Because the `for await` pattern is async, it means that the consumption of the query results and the cancellation of the statement will be coroutines relative to each other.

With the above in mind, there are some questions that seem unanswered in the documentation, and I can really do with some complete code examples to demonstrate:
1. What happens when the result-consuming coroutine awaits a row after I have issued `statement.cancel()` in the other statement-cancelling coroutine? Can I expect an error to be thrown in the result-consuming coroutine? If so, what are the exact error `code`, `message`, or `sqlState` I can expect, for example? Or can I expect the `streamRow()` to simply stop giving me more rows? Or something like giving me `undefined` as the last row?
2. How do I know whether it is still safe to cancel a statement? Is it meaningless to cancel a statement as soon as the first row of the result is available to the result-consuming coroutine?

**Comment by sfc-gh-dszmolka** [comment]
hi, thank you for raising this issue. going forward, we need the community to submit their requests to their appropriate places:
* production affecting issues originating from snowflake-sdk: kindly [raise a case with Snowflake Support](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge)
* issues and feature requests: please do raise an Issue in this repo. (Note: for feature requests, there's no timeline guarantee on the response or the implementation)
* usage advice, 'how to do..': kindly post to [Snowflake Stackoverflow](https://community.snowflake.com/s/article/Snowflake-Community-on-Stack-Overflow-Know-Before-You-Go)

with that said, I'm now marking this Issue as closed. please feel free to reopen it if you think this is caused due to a bug. in that case, we'll kindly request you to post a reproduction code snippet, which when run, can reproduce the issue you're having. thank you in advance !
