### ISSUE TITLE
Backward incompatible interface change in patch version 1.1.15

### ISSUE THREAD

**Issue by countergram** [snowflakedb/snowflake-connector-nodejs#45]
1.1.15 introduced a backward incompatible change to numeric output types in a patch version, which breaks existing code and cannot easily be avoided due to the patch version. 

Run the following on 1.1.14 and 1.1.15:

```
sf.connect(() => {
    sf.execute({
      sqlText: 'select 1',
      complete: (err, stmt, rows) => {
        console.log(rows);
      }
    });
  });
```

Output under 1.1.14:

```
[ { '1': 1 } ]
```

Output under 1.1.15:

```
[ { '1': Integer { value: 1n } } ]
```

This Integer here is of type `object` and is JSON serialized to a string `"1"` rather than to a number `1`.

The behavior also contradicts the published documentation at https://docs.snowflake.net/manuals/user-guide/nodejs-driver-use.html#data-type-casting (JavaScript data type: `Number`)

**Comment by smtakeda** [comment]
Sorry about inconvenience. The documentation update is behind.
This is due to the change in https://github.com/snowflakedb/snowflake-connector-nodejs/commit/8cf1a6616f74e8331e48549c11a5c4bb63941ee4
> SNOW-75968: return the column as a BigInteger if a column is returned back as type FIXED and scale is equal to zero, otherwise return REAL
Pre-announced at https://community.snowflake.com/s/article/3-29-Release-Notes

Anyway one way to mitigate it is add another condition when determining the type in columns.js, e.g,.
```
    if (this.getScale() > 0 || this.getPrecision() < 17 || this.getType() === SqlTypes.values.REAL)
    {
      convert  = convertRawNumber;
    }
    // This is a integer so represent it as a big int
    else
    {
      convert  = convertRawBigInt;
    }
```

**Comment by SkylerWilliams** [comment]
I believe the 3-29 Release Notes are incorrect in saying `Values retrieved from Snowflake are stored as JavaScript BIGINT if those retrieved values are FIXED DECIMAL and have a scale of 0 (i.e. no digits after the decimal point)`. It appears that the BigInteger [library](https://github.com/peterolson/BigInteger.js) imported in [`column.js`](https://github.com/snowflakedb/snowflake-connector-nodejs/commit/8cf1a6616f74e8331e48549c11a5c4bb63941ee4#diff-2c75e80d59ab951889ee5161d7399826R10) is actually a wrapper around the native Javascript `BigInt` type, and therefore `typeof` will return `object` rather than `bigint` as would be the [case](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Type_information) with the Javascript type. So, in order to determine the type of the returned columns, one needs to use the [`isInstance()`](https://github.com/peterolson/BigInteger.js#isinstancex) static method within the BigInteger library rather than just the built in `typeof`.

**Comment by smtakeda** [comment]
@notkriswagner can you look into this?

**Comment by notkriswagner** [comment]
@SkylerWilliams The release notes are incorrect. We originally used the BigInteger library to allow everyone to take advantage of the BigInteger type regardless of the version of NodeJS that the driver is running on.

One of the solutions we are thinking of is to only return a Javascript BigInt if the driver is running on NodeJS 10.4+ and will return a Number if the driver is running on an older version of NodeJS. @SkylerWilliams  and @countergram would this solution solve your issues?

**Comment by countergram** [comment]
That would still be a backward incompatible interface change to the library, particularly from the perspective of JSON serialization since BigInt is not JSON serializable out of box.

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
```

**Comment by countergram** [comment]
Is there any chance of reverting this change in a new patch version while preparing whatever you have planned for a (perhaps major) version? We continue to find places where this broke code and it's leading to customer impacting issues. For example, when casting a Number to a bool to check for the presence of something, 0 is falsy, but with the new object return value, the object is truthy since the actual value is inside. This has led to incorrect data exports since the new version was taken up. Again, since this was a patch version it's hard to pin back when getting it through `snowflake-promise` (believe it takes manually editing package-lock on every update).

**Comment by chriskinsman** [comment]
This broke us tonight also and we had to roll back to 1.1.13 to return to old behavior...

**Comment by smtakeda** [comment]
OK, we'll drop 1.1.15 to leave the old behavior in the series of 1.1.x.
Meanwhile, we'll find out the better approach to address both `BigInt` and old behavior needs in the series of 1.2.x. It is very likely to have a parameter for NodeJS driver. Potentially `CLIENT_TREAT_DECIMAL_AS_INT` for all drivers similar to https://docs.snowflake.net/manuals/sql-reference/parameters.html#jdbc-treat-decimal-as-int

I admit it was our mistake to bump up the patch version for this change but should have been minor version.

**Comment by smtakeda** [comment]
It appeared we cannot drop the package but all we can do is deprecate it:
https://www.npmjs.com/package/snowflake-sdk/v/1.1.15

**Comment by miguelb** [comment]
We also ran into this issue and had to revert back to the previous version. However, we ran into when using "COUNT". We also tried upgrading to the latest 1.2.x, same is problem. 
So moving forward, "COUNT" will also be wrapped in the bigint object? This will be a big change for us to make throughout our analytics platform and don't see us moving out of 1.1.14 any time soon.

**Comment by chriskinsman** [comment]
We are in the same boat. This change essentially orphans us on 1.11.14. Due to aggregates like count now returning bigint the number of places in our code this would affect is enormous. We need a way to disable this behavior that will allow us to continue to pick up servicing releases....

**Comment by smtakeda** [comment]
In 1.3.0:
- The default mapping is changed back to `NUMBER(n,m)` database type to `Number` JS type.
- `JS_TREAT_INTEGER_AS_BIGINT` is introduced to change `NUMBER(n,0)` database type to `BigInt`

**Comment by chriskinsman** [comment]
Is there any documentation on JS_TREAT_INTEGER_AS_BIGINT yet?  Couldn't find anything.

**Comment by smtakeda** [comment]
The ticket for doc update is in the queue. Bumped the priority.

**Comment by smtakeda** [comment]
The ticket for doc update is in the queue. Bumped the priority.
