### ISSUE TITLE
SNOW-955496: Release the currently unrelease changes please

### ISSUE THREAD

**Issue by Obi-Dann** [snowflakedb/snowflake-connector-nodejs#682]
Hello,

Would it be possible to release the currently unreleased changes please?

We're mainly keen to get https://github.com/snowflakedb/snowflake-connector-nodejs/pull/641 into a release versions, because currently we're experiencing a major prod issue due to running out of connections.
Essentially, every query creates a new connection and nothing disposes of them ATM.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue ! we ask for a couple more days of patience please. The release cycle is currently in progress and I expect to release the Snowflake nodejs driver in the coming days. 

In the meantime if getting the latest fixes is very important, you can right now take advantage of the change in 641 by installing the package from git, for example with npm:
`npm install https://github.com/snowflakedb/snowflake-connector-nodejs.git`

will install the latest code, no matter if it's released or unreleased.
Alternatively you could look into using [ConnectionPool](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-connect#creating-a-connection-pool) instead of individual connections, if you're not already doing that. It also has a builtin mechanism of getting rid of idle connections if you set `evictionRunIntervalMillis` to a non-zero value, e.g. 30000 will run the evictor in every 30 seconds.

**Comment by Obi-Dann** [comment]
I am not sure using ConnectionPool would help. We're actually using a single "snowflake" connection object, but it creates a new http connection on every request.
On this line, a new http agent is created that holds all the HTTP connections https://github.com/snowflakedb/snowflake-connector-nodejs/blob/75d429ae6f654323d1c954b98b437ac8d261eef0/lib/http/base.js#L103.
It'd might be OK if the http agent was destroyed (released) after use, but it's left. So the HTTP connections are only released in 2 minutes (after some timeout).
Essentially, http agents should be reused rather than created and thrown away.

**Comment by sfc-gh-dszmolka** [comment]
got you, thanks for putting more light on the situation ! in this case hopefully #641 can help, you can test it right now using the above (or similar) method of installing the code from `main` but i'll update this issue once the release is out.

**Comment by Obi-Dann** [comment]
Thanks, we followed the advice and installed snowflake-sdk from the merge commit of #641 https://github.com/snowflakedb/snowflake-connector-nodejs/commit/35869a8de5bb48131684c0b23768824f8f988db7

The issue is completely resolved now, looking forward to switching to a properly released version when it's ready 👍

**Comment by sfc-gh-dszmolka** [comment]
we hope to have tackled the roadblock which caused release delays in the drivers (including `snowflake-sdk`) so hopefully it'll be out this week 🤞

**Comment by sfc-gh-dszmolka** [comment]
node.js driver version 1.9.1 released with the fix and is available on npm. thank you all for bearing with us !
