### ISSUE TITLE
SNOW-1367369: Allow passing passcode for DUO MFA

### ISSUE THREAD

**Issue by mcastany** [snowflakedb/snowflake-connector-nodejs#838]
## What is the current behavior?
I cannot configure the SDK with passcode and I'm spamming DUO push notifications to my device everytime I want to execute a script

## What is the desired behavior?
I can setup my DUO mfa passcode and be able to connect to Snowflake without a push notification

**Comment by sfc-gh-dszmolka** [comment]
hi - I know the current behaviour is mildly annoying .. fortunately, the works are already in progress to add MFA caching capability for this driver too. Tracking issue is https://github.com/snowflakedb/snowflake-connector-nodejs/issues/493, I recommend subscribing to those updates.

After the capability is implemented and a new driver version is released on top of the (future) merged PR, you won't need to spam and be spammed by DUO notifications after enabling the MFA caching feature on the [server-side](https://docs.snowflake.com/en/user-guide/security-mfa#using-mfa-token-caching-to-minimize-the-number-of-prompts-during-authentication-optional) and driver side too. (server-side already supports this, however the `snowflake-sdk` driver not yet)

Hope this answers your question - also would like to recommend closing this issue and following the other one linked here.

**Comment by mcastany** [comment]
@sfc-gh-dszmolka TBH, I don't mind the spam that much, but the other day my account got locked. Do you know if there's any limit of push notifications from Duo?

**Comment by sfc-gh-dszmolka** [comment]
this is two independent things. For one, your Snowflake user [will get locked temporarily](https://community.snowflake.com/s/article/User-temporarily-locked-Contact-your-local-system-administrator-or-please-create-a-case-with-Snowflake-Support-or-reach-us-on-our-support-line), regardless of the authentication method and MFA/no MFA, if there are too many unsuccessful login attempts. This temporal lock should also disappear on its own after 15 minutes.

For the rate limit on the DUO authentication API, that's not managed by Snowflake but they probably have a rate limit. It should be transparent to the Snowflake user.

Hope this clarifies but please let me know if you have any other questions. Otherwise, I suggest closing this duplicate issue and following the linked one for the feature implementation.
